name = "MapMakie"
uuid = "fe52baaf-6d3a-4a5f-a57b-73f45372fb58"
authors = ["Simon Etter <ettersi@users.noreply.github.com>"]
version = "0.1.3"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MapMaths = "0922fada-4501-4821-9da5-5833bcb2b8d4"
TileProviders = "263fe934-28e1-4ae9-998a-c2629c5fede6"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
FileIO = "1.16"
HTTP = "1.10"
IntervalSets = "0.7.8"
LRUCache = "1.6"
Makie = "0.20"
MapMaths = "0.1"
TileProviders = "0.1.3"
Unitful = "1.19"
julia = "1.9"
